### ISSUE TITLE
gsoc project contribution

### ISSUE THREAD

**Issue by ericglem** [invesalius/gsoc#1]
Hey guys!

I saw this project on the Google Summer of Code site and I'm really interested in contributing. I don't know if there is a better channel for communication, so I decided to create this issue.

**Title of the project**:  _Add unit tests to InVesalius to ease the process of adding new features_.

I'm currently a back-end developer working with Python as a primary programming language, so working on this seems to fit pretty well with my skills. I hope I can catch with you guys to discuss more on this!

Cheers!

**Comment by paulojamorim** [comment]
Hi @ericglem ,

Thanks for your interest! We will put the guidelines here (github) soon.

**Comment by paulojamorim** [comment]
@ericglem ,

We publish the instructions for applicants here: https://github.com/invesalius/gsoc/blob/main/gsoc_application.md

Please, follow the instructions.
